apiVersion: v2
name: cert-manager-webhook-solidserver
description: Allow cert-manager to solve DNS challenges using the SOLIDserver API
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/niklas-letz/cert-manager-webhook-solidserver
icon: https://raw.githubusercontent.com/cert-manager/cert-manager/master/logo/logo-small.png
keywords:
  - cert-manager
  - solidserver
  - letsencrypt
  - tls
sources:
  - https://github.com/niklas-letz/cert-manager-webhook-solidserver
  - https://github.com/cert-manager/webhook-example
maintainers:
  - name: Niklas Letz
annotations:
  artifacthub.io/license: Apache-2.0
